### ISSUE TITLE
Bug: Table skeletons shrinks horizontally the columns

### ISSUE THREAD

**Issue by EmanueleQuerzola** [wonderflow-bv/wanda#103]
### What happened?

When in the table is active the loading state the skeleton shrinks the columns horizontally creating  a strange visual effect

### Version

6.0.0

### React and ReactDOM version

17.0.2

### What browsers are you seeing the problem on?

All

### Code of Conduct

- [X] I've searched across open and closed issues for similiar bug reports

**Comment by equinusocio** [comment]
This should be fixed in blind.
