### ISSUE TITLE
Autocomplete props

### ISSUE THREAD

**Issue by alessio-libardi** [wonderflow-bv/wanda#133]
### Feature description

Enhance the `<Autocomplete />` component adding a couple of useful props:

- `iconPosition`
- `loading`

## Icon position

I'm not sure if there was a reason the `iconPosition` prop isn't available, should the search icon always be on the right for a special reason? Otherwise it would be cool to have this property to decide where to place it. Maybe from a consistency point of view having it always on one side would be best?

## Loading status

Having a `loading` prop to show a spinner or a skeleton would be cool, it can be easily done using a snowflake and the skeleton component but maybe, consistently handling this prop on the DS would be better.

This prop would be used while loading the items of the autocomplete and also when searching in a large database and typing on the autocomplete would load other entries.

Following a video showcasing what I tought could be a solution:

https://user-images.githubusercontent.com/58233289/164181554-d3c8a480-2892-4f8b-8968-9ae63290b82f.mov

Let me know what you think 🙌 

### Code of Conduct

- [X] I've searched across open and closed issues for similiar requests

**Comment by equinusocio** [comment]
About the first request, textfield props are already available.

https://design.wonderflow.ai/components/inputs/autocomplete#autocomplete
![Screenshot 2022-04-21 at 14 39 22](https://user-images.githubusercontent.com/10454741/164459789-abc199ee-5807-4e84-935b-c2f2cab1dafe.png)

For the second one I need to do some investigation

**Comment by equinusocio** [comment]
Ref. https://github.com/wonderflow-bv/wanda/pull/122
