### ISSUE TITLE
Change `Autocomplete` `onChange` event to be a real `Event` fired from the `input` element

### ISSUE THREAD

**Issue by alessio-libardi** [wonderflow-bv/wanda#143]
### Feature description

I would like the `onChange` event be a real `Event` fired from the `input` component to easily integrate the `Autocomplete` component with libraries managing forms and inputs.

Trying to integrate `react-hook-form` using uncontrolled state is giving the current error when changing the autocomplete value:
![Screenshot 2022-05-02 at 11 15 49](https://user-images.githubusercontent.com/58233289/166212149-223fb821-504b-44b3-8906-3952f344dfc3.png)

### Describe the solution you'd like

The solution I would like is to have the `onChange` event be a real `Event` fired from the `input` component the `ref` prop is forwarded to.

### Additional context and information

We need this feature to easily integrate `react-hook-form` hooks into our toolbelt. Without this we can integrate the autocomplete but in a more manual and tedious way because we need to control the input ourselves, making the process possibly error prone.

### Code of Conduct

- [X] I've searched across open and closed issues for similiar requests

**Comment by equinusocio** [comment]
Currently, `onChange` prop refers to option picking. Maybe the name is misleading. In any case, the textfield already uses the `onChange` event to filter options inside the autocomplete, so it cannot be used to detect the picked value.

**Comment by equinusocio** [comment]
`onChange` event and the forwarded `ref` are now bound to the `input` element
