### ISSUE TITLE
Bug: Match `dimmed` prop to `dimmed` token in `<Card />` component

### ISSUE THREAD

**Issue by alessio-libardi** [wonderflow-bv/wanda#167]
### What happened?

The `<Card />` component `dimmed` prop accepts values `1 | 2 | 3` but underneath use them as `0 | 1 | 2`.

This can create confusion, let's simplify it and align the `dimmed` prop usage.

### Version

9.3.0

### Code of Conduct

- [X] I've searched across open and closed issues for similiar bug reports

**Comment by equinusocio** [comment]
Releasing
https://github.com/wonderflow-bv/wanda/pull/168
