### ISSUE TITLE
Table: select all checkbox doesn't shows up on manual pagination

### ISSUE THREAD

**Issue by EmanueleQuerzola** [wonderflow-bv/wanda#206]
### What happened?

When using the table with the manual pagination the checkbox to select all items on the headers of the table disappear

### Version

10.1

### React and ReactDOM version

17.0.2

### What browsers are you seeing the problem on?

All

### Code of Conduct

- [X] I've searched across open and closed issues for similiar bug reports

**Comment by equinusocio** [comment]
Issue is caused by this check:
https://github.com/wonderflow-bv/wanda/blob/main/packages/react-components/src/components/table/table.tsx#L289
