### ISSUE TITLE
Table: disable some checkboxes in row selection

### ISSUE THREAD

**Issue by alessiatovo** [wonderflow-bv/wanda#207]
### Feature description

In the Table component, when the `selectableRows` property is set to True, could be useful to have the possibility to disable the checkbox for some rows, depending on the row value or other parameters.
Also, when you select all the rows, those rows that have the checkbox disabled, should not appears in the `selectedRowIds` array.

### Code of Conduct

- [X] I've searched across open and closed issues for similiar requests

**Comment by equinusocio** [comment]
After some research it seems we cannot have this option. The row selection feature provided by react-table doesn't provide a way to disable selection on specific rows. Even by hiding the checkbox, when pressing the "select all" control all the rows will be selected anyway.
