### ISSUE TITLE
Menu component -> menu item to support subtext

### ISSUE THREAD

**Issue by Lizfernan** [wonderflow-bv/wanda#210]
### Feature description

Please add a new property to menu item to contain subtext below the label.
This subtext should wrap if needed. 

![Screenshot 2022-07-18 at 17 07 09](https://user-images.githubusercontent.com/103127163/179546636-740dbaac-8bb1-4263-a6e3-a8f9a29d415c.png)
 

### Code of Conduct

- [X] I've searched across open and closed issues for similiar requests

**Comment by equinusocio** [comment]
What is the context of this? Figma?

**Comment by Lizfernan** [comment]
FIgma and code. We need to be able to support this in the overall panel (as its now called) menu to display topic levels.

**Comment by equinusocio** [comment]
Code side is already possible. On Figma we cannot shipp this change within the DS since is a snowflake and atm we still don't have an official way to use slot inside components.

**Comment by Lizfernan** [comment]
Great! I don't see why we need a Slot here, we know that this subtext should only contain a string - at least for now.
