### ISSUE TITLE
InfoState component should accept as children not only text

### ISSUE THREAD

**Issue by EmanueleQuerzola** [wonderflow-bv/wanda#216]
### Feature description

As children of the info state componet we can only put tags that can be descendant of the `<p>` tag.
But in some cases we need to add extra information formatted in some ways such as a list

### Describe the solution you'd like

Personally I would add a new prop on the info state called `message` which represents the message of the info state and that it can be only text. 
And then let add as children props any component the user want an place it between the message and the actions.

### Describe alternatives you've considered

We can also let the user add the message and the other extra informations as children of the info state

### Additional context and information

<img width="462" alt="Screenshot 2022-07-25 at 18 06 20" src="https://user-images.githubusercontent.com/84083411/180824236-74b71a1b-bf0d-4be4-8d81-81d8ccaaeaf9.png">

### Code of Conduct

- [X] I've searched across open and closed issues for similiar requests

**Comment by equinusocio** [comment]
> Personally I would add a new prop on the info state called message which represents the message of the info state and that it can be only text.
And then let add as children props any component the user want an place it between the message and the actions.

This change leads to a breaking change because removing the pre-formatted text will require consumers to add the `Text` component (with the same style) on their own.
