### ISSUE TITLE
Table expanded rows background-color 

### ISSUE THREAD

**Issue by Lizfernan** [wonderflow-bv/wanda#224]
### Feature description

"Users can’t see much difference between parent and children topic because the blue shades used are too similar" 

Link here: https://airtable.com/appScoljSIFwYrYhn/tblO9kOg2fDTp1Pwa/recc9CJA5tRjDmVlD

### Describe the solution you'd like

Change the background-color of the of expanded rows to a different shade so differentiation is more obvious to our users.

### Code of Conduct

- [X] I've searched across open and closed issues for similiar requests

### Project assignment

- [X] I've assigned Wanda Design System project from the sidebar on the right.

**Comment by equinusocio** [comment]
Please follow the governance process.
