### ISSUE TITLE
Bug: Table selecteableRows set to false remove Table title and Actions

### ISSUE THREAD

**Issue by alessiatovo** [wonderflow-bv/wanda#266]
### What happened?

In the Table component, if the prop `selectableRows` is set to False, the Page title and the Actions are not visible anymore.

### Version

10.6.0

### What browsers are you seeing the problem on?

All

### Code of Conduct

- [X] I've searched across open and closed issues for similiar bug reports

### Project assignment

- [ ] I've assigned Wanda Design System project from the sidebar on the right.

**Comment by equinusocio** [comment]
http://design.wonderflow.ai/get-started/components/layouts/table#prop-showheader
