### ISSUE TITLE
Chip with left icon

### ISSUE THREAD

**Issue by wonder-terry** [wonderflow-bv/wanda#268]
### Feature description

Currently we have a chip component which is interactive making it dismissible. That is the only icon that appears in the chip component.

### Describe the solution you'd like

A need has come up for an icon to be added to the chip, on the left of the text, making the chip more of an informational tool. Like a label describing the state of an element, such as a locked dashboard. Ideally, if the chip has an icon to the left of the text, then it cannot be dismissible. When there is no icon to the left, it can be dismissed, for functions such as filters.

### Describe alternatives you've considered

Describing the state something in words, ie. "Locked" but no reason as to why it's locked. Having a variation of the chip, where you can insert an icon on the left of the text in the chip, making it an informational label. This type of icon can not be dismissed. If a dismissible icon is being used, then there can be no icon to the left. Icon would be the same size as the dismiss icon, 12px.

<img width="185" alt="Screenshot 2022-11-14 at 12 28 07" src="https://user-images.githubusercontent.com/112939091/201649811-5c6485a5-b4ef-4908-9681-fbff22e0f546.png">

### Code of Conduct

- [X] I've searched across open and closed issues for similiar requests

### Project assignment

- [X] I've assigned Wanda Design System project from the sidebar on the right.

**Comment by equinusocio** [comment]
@wonder-terry Reading the requirements i see we want to give `dismissable` higher priority over `icon`. This means if icon is set, but then `dismissable` is set also to `true`, the `icon` on the left will be remove. Is that ok?

**Comment by wonder-terry** [comment]
@equinusocio, yes, correct. That is okay.

**Comment by equinusocio** [comment]
Feature request released 👍
