### ISSUE TITLE
Bug: wrong link in home

### ISSUE THREAD

**Issue by equinusocio** [wonderflow-bv/wanda#270]
### What happened?

This read more link is broken. Should point to https://design.wonderflow.ai/get-started/documentation/design/themes

![CleanShot 2022-11-18 at 17 56 02](https://user-images.githubusercontent.com/10454741/202759597-aedf60e0-c320-41f2-a6a8-32e4ff2ce170.png)

### Version

*

### What browsers are you seeing the problem on?

All

### Code of Conduct

- [X] I've searched across open and closed issues for similiar bug reports

### Project assignment

- [X] I've assigned Wanda Design System project from the sidebar on the right.

**Comment by patricktabar** [comment]
fixed broken link in homepage
