### ISSUE TITLE
Bug: Typo on the website banner

### ISSUE THREAD

**Issue by amartadey** [wonderflow-bv/wanda#283]
### What happened?

There is a typo on the banner of the landing page.
"enojoyable" should be "enjoyable"
![Screenshot](https://user-images.githubusercontent.com/34670651/211269855-4f1138ea-bc0e-422c-b956-39442dbdd92d.png)
Thanks

### Version

Website Landing Page

### Code of Conduct

- [X] I've searched across open and closed issues for similiar bug reports

### Project assignment

- [X] I've assigned Wanda Design System project from the sidebar on the right.

**Comment by design-wonderflow** [comment]
thank you @amartadey
