### ISSUE TITLE
Bug: Remove the animated carousel from the home page

### ISSUE THREAD

**Issue by impressivewebs** [wonderflow-bv/wanda#284]
### What happened?

The animated carousel on the home page has absolutely awful performance and just about freezes and crashes my browser any time I visit the page. I'm planning on including Wanda on a year-end post I do annually for "top tools of 2022", but I'm going to have to link to the GitHub repo, rather than the home page, due to this performance problem on the home page.

### Version

Website, not software

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I've searched across open and closed issues for similiar bug reports

### Project assignment

- [X] I've assigned Wanda Design System project from the sidebar on the right.

**Comment by design-wonderflow** [comment]
Can you provide more technical details on "absolutely awful performance" and "freezes and crashes my browser", since we cannot reproduce your issue. Thanks

**Comment by impressivewebs** [comment]
More than likely it works fine on a high performance system. I'm on Windows 10 using Chrome, Brave, and Firefox, same basic result in all, it just makes everything on the page and in the browser slow down.

If I try to scroll down the page, the performance on the page is very choppy and eventually the tab slows down considerably almost freezing the browser. I'm not sure what other technical info I can provide.

Might be good to run some tests on a slower/older system if possible (mine is maybe 4-5 years old).

And FYI - The Wanda design system is a cool project, and it's nice to see a project like this based on good principles. I probably should have mentioned that up front, sorry about the rude tone in the first post! :)
