### ISSUE TITLE
Wonderflow icon

### ISSUE THREAD

**Issue by bitliner** [wonderflow-bv/wanda#303]
### Icon names

wonderflow

### Icons proposal

an icon that contains the wonderflow logo

### Code of Conduct

- [X] I've searched across open and closed issues for similiar requests

### Project assignment

- [X] I've assigned Wanda Design System project from the sidebar on the right.

**Comment by bitliner** [comment]
It could be placed anywhere.
In a chat, it comes handy for distinguishing the user (with the user icon) from Wonderflow (with the Wonderflow icon)

**Comment by Lizfernan** [comment]
If its placed on the chat conversation, then we would recommend using an avatar component with the Wonderflow image. Its important to consider the context in which the icon will be used and ensure that they are appropriate for the specific component or interface they will be a part of. For example if you need this icon on a button, then we need to create a new solid Wondeflow icon as our button component only use solid styles.
