### ISSUE TITLE
New icons request for "verified" checkmark

### ISSUE THREAD

**Issue by bitliner** [wonderflow-bv/wanda#309]
### Icon names

- verified

### Icons proposal

The icon "Verified" wants to communicate that something has been "verified" (=submitted to a certain control or quality procedure). Helpful in AI applications, where sometimes there is the need to communicate the superior level of reliability of certain outputs.

### Code of Conduct

- [X] I've searched across open and closed issues for similiar requests

### Project assignment

- [X] I've assigned Wanda Design System project from the sidebar on the right.

**Comment by design-wonderflow** [comment]
![image](https://github.com/wonderflow-bv/wanda/assets/82821180/73fcf58b-fb15-4b89-81f9-0ce5ac96eb38)
just for reference
