### ISSUE TITLE
Bug: modal overlay, tooltips and popover z-index issues

### ISSUE THREAD

**Issue by andreapavia** [wonderflow-bv/wanda#341]
### What happened?

The overlay container implemented in the `Modal` component has a default `z-index` value of 4; other elements, such as tooltips have a `z-index `of 5 and can be visible above a modal when opened:

![Screenshot 2023-12-18 at 15 29 12](https://github.com/wonderflow-bv/wanda/assets/38351726/5a9a4bfb-cd3b-4890-8529-389f667ef952)
As it is visible in the screenshot above, opening a modal from a `Popover` inside a `Menu` in a `Table` action will result in the menu still being visible above the overlay.

![Screenshot 2023-12-18 at 15 29 12](https://github.com/wonderflow-bv/wanda/assets/38351726/7e0cf184-a257-433b-8322-2fd0f9de5ce8)
As it is visible in the screenshot above, opening a modal from a tooltip will result in te tooltip's baloon being visible as a square on the screen.

A possible fix to this is setting a custom index prop on the modal which will be passed down to the `OverlayContainer` component inside the `Modal`, but this is more of a hackfix and could potentially interfere and break with Wanda's handling of indexes.

### Version

12.6

### React and ReactDOM version

17.0.2

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I've searched across open and closed issues for similiar bug reports

### Project assignment

- [X] I've assigned Wanda Design System project from the sidebar on the right.

**Comment by design-wonderflow** [comment]
@andreapavia menu shouldn't stay open once the modal is, we likely have a bug on the menu component not reacting at focus change
