### ISSUE TITLE
Tooltip triggerable on disabled element

### ISSUE THREAD

**Issue by alessiatovo** [wonderflow-bv/wanda#355]
### Feature description

The Tooltip component needs a trigger props. If you have as trigger an element that somehow overwrite the hover functionalities, disabling them, the Tooltip content is not triggered. For example if you implement something like 

`<Tooltip trigger={<Button disabled>Click me</Button>}>Tooltip message to visualize</Tooltip>`

the content _Tooltip message to visualize_ is not rendered.

### Describe the solution you'd like

I would like to have a Tooltip that always follow the trigger element interaction, regardless of its implementation.

### Code of Conduct

- [X] I've searched across open and closed issues for similiar requests

### Project assignment

- [X] I've assigned Wanda Design System project from the sidebar on the right.

**Comment by design-wonderflow** [comment]
This is a common limitation since disabled HTML elements don't fire mouse events. To handle disabled elements, a workaround is to use an element such as a span, as a simple wrapper element.
