### ISSUE TITLE
Bug: Tailwind compatibility

### ISSUE THREAD

**Issue by MuhammadSawalhy** [wonderflow-bv/wanda#358]
### What happened?

I want to use Tailwind CSS with this wonderful library. I read in your [docs ](https://design.wonderflow.ai/get-started/documentation/develop/installation#known_issues) that versions higher than 10 don't support Tailwind, but why??! Tailwind is also wonderful.

> Wanda versions >10.6 are no longer compatible with Tailwind CSS.

### Version

14

### Code of Conduct

- [X] I've searched across open and closed issues for similiar bug reports

### Project assignment

- [X] I've assigned Wanda Design System project from the sidebar on the right.

**Comment by design-wonderflow** [comment]
Tailwind CSS was not compliant anymore with our design and implementation choices therefore we stopped supporting it and we are not looking forward to support it in the future.
