### ISSUE TITLE
FR: Icon property descriptions are not clear about the icon weight/size

### ISSUE THREAD

**Issue by alessio-libardi** [wonderflow-bv/wanda#87]
### What happened?

Hello, by deafult the icon `weight` is set to `outline` while the docs says otherwise. What's the truth?

![Screenshot 2022-03-01 at 15 42 23](https://user-images.githubusercontent.com/58233289/156189807-39c97849-4adb-4ae8-aa3a-3b72b5825b2c.png)

Thanks 🙌 

### Version

Live website (5.5 i presume)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I've searched across open and closed issues for similiar bug reports

**Comment by equinusocio** [comment]
Ready to be released
https://github.com/wonderflow-bv/wanda/pull/88

**Comment by alessio-libardi** [comment]
Thanks, indeed the issue arised from the property description of `weight`, now everything is clear 🙌
