### ISSUE TITLE
Bug: Tooltip doesn't disappear on focus outside

### ISSUE THREAD

**Issue by alessio-libardi** [wonderflow-bv/wanda#89]
### What happened?

The `<Tooltip />` component correctly works when hovering the trigger. When instead we use the keyboard to navigate and we **focus** the trigger of a tooltip, when we **unfocus** the trigger the `<Tooltip />` content doesn't disappear.

Here a simple video showing the issue:

https://user-images.githubusercontent.com/58233289/156530969-427d554a-39b9-4988-bac2-794d67455a59.mov

### Version

Live docs

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I've searched across open and closed issues for similiar bug reports

**Comment by equinusocio** [comment]
Ready in https://github.com/wonderflow-bv/wanda/pull/91
