### ISSUE TITLE
Open/close dropdown programmatically

### ISSUE THREAD

**Issue by alessiatovo** [wonderflow-bv/wanda#90]
### Feature description

It could be nice to have the possibility to open/close the Dropdown in a different ways than the `esc` press or the changing of focus, like for example open/close it using Buttons/Links/event handlers

### Code of Conduct

- [X] I've searched across open and closed issues for similiar requests

**Comment by equinusocio** [comment]
Ready in https://github.com/wonderflow-bv/wanda/pull/91

**Comment by equinusocio** [comment]
We introduced a bunch of new properties to use the Dropdown as `controlled` component
